{
proj: { code:'sp', name:'Приобретение программы', projVer:2, curTime:'17.01.2007  08:00'},
operations: [
{ level:null,code:'spamrd01',name:'Управление 1',actualStart:'09 01 2007  08 00',actualFinish:'10 01 2007  16 00',asapStart:'',asapFinish:'',compareStart:'',compareFinish:'', critical:null, costTotal:1234, volSum:100, durSumD:2,},
{ level:null,code:'spamrd02',name:'Демонстрации',actualStart:'09 01 2007  12 00',actualFinish:'11 01 2007  12 00',asapStart:'',asapFinish:'',compareStart:'',compareFinish:'', critical:null, costTotal:1410, volSum:100, durSumD:2,},
{ level:null,code:'',name:'Длительность',actualStart:'',actualFinish:'',asapStart:'18 01 2007  16 00',asapFinish:'17 01 2007  08 00',compareStart:'',compareFinish:'', critical:null, costTotal:16, volSum:null, durSumD:6,},
{ level:null,code:'spammr02',name:'Анализ рынка ПО',actualStart:'',actualFinish:'',asapStart:'19 01 2007  08 00',asapFinish:'22 01 2007  16 00',compareStart:'',compareFinish:'', critical:null, costTotal:1175, volSum:100, durSumD:2,},
{ level:null,code:'spamrd04',name:'Разработка критериев отбора',actualStart:'',actualFinish:'',asapStart:'24 01 2007  08 00',asapFinish:'25 01 2007  16 00',compareStart:'',compareFinish:'', critical:null, costTotal:3434, volSum:100, durSumD:2,},
{ level:null,code:'spammr03',name:'Бизнес аналитик',actualStart:'',actualFinish:'',asapStart:'25 01 2007  16 00',asapFinish:'25 01 2007  16 00',compareStart:'',compareFinish:'', critical:null, costTotal:205, volSum:100, durSumD:null,},
{ level:null,code:'spscsa02',name:'Рассылка RFP',actualStart:'',actualFinish:'',asapStart:'02 02 2007  08 00',asapFinish:'05 02 2007  10 00',compareStart:'',compareFinish:'', critical:null, costTotal:504, volSum:5, durSumD:1.25,},
{ level:null,code:'spscsa03',name:'Список поставщиков',actualStart:'',actualFinish:'',asapStart:'02 02 2007  08 00',asapFinish:'08 02 2007  16 00',compareStart:'',compareFinish:'', critical:null, costTotal:1944, volSum:5, durSumD:5,},
{ level:null,code:', стоимость)',name:'Длительность',actualStart:'',actualFinish:'',asapStart:'12 02 2007  16 00',asapFinish:'09 02 2007  08 00',compareStart:'',compareFinish:'', critical:null, costTotal:32, volSum:null, durSumD:2,},
{ level:null,code:'spscic01',name:'Создание короткого списка',actualStart:'',actualFinish:'',asapStart:'13 02 2007  08 00',asapFinish:'15 02 2007  16 00',compareStart:'',compareFinish:'', critical:null, costTotal:1313, volSum:3, durSumD:3,},
{ level:null,code:'spscic02',name:'Анализ демо версий',actualStart:'',actualFinish:'',asapStart:'13 02 2007  08 00',asapFinish:'14 02 2007  12 00',compareStart:'',compareFinish:'', critical:null, costTotal:594, volSum:3, durSumD:1.5,},
{ level:null,code:'spscnc01',name:'Проверка поддержки',actualStart:'',actualFinish:'',asapStart:'16 02 2007  08 00',asapFinish:'16 02 2007  16 00',compareStart:'',compareFinish:'', critical:null, costTotal:1346, volSum:2, durSumD:1,},
{ level:null,code:'spscnc02',name:'Управление 2',actualStart:'',actualFinish:'',asapStart:'19 02 2007  08 19',asapFinish:'20 02 2007  08 19',compareStart:'',compareFinish:'', critical:null, costTotal:1337, volSum:2, durSumD:1,},
{ level:null,code:'spscnc03',name:'Переговоры2',actualStart:'',actualFinish:'',asapStart:'20 02 2007  08 19',asapFinish:'22 02 2007  08 19',compareStart:'',compareFinish:'', critical:null, costTotal:3433, volSum:100, durSumD:2,},
{ level:null,code:'spscsa01',name:'Анализ спецификаций',actualStart:'',actualFinish:'',asapStart:'02 02 2007  08 00',asapFinish:'02 02 2007  08 00',compareStart:'',compareFinish:'', critical:null, costTotal:17, volSum:5, durSumD:null,},
{ level:null,code:'',name:'Длительность',actualStart:'',actualFinish:'16 01 2007  08 00',asapStart:'23 01 2007  16 00',asapFinish:'23 01 2007  08 00',compareStart:'',compareFinish:'', critical:null, costTotal:24, volSum:null, durSumD:2,},
{ level:null,code:'spscsa05',name:'Получение предложений',actualStart:'',actualFinish:'',asapStart:'05 02 2007  10 00',asapFinish:'05 02 2007  12 30',compareStart:'',compareFinish:'', critical:null, costTotal:166, volSum:5, durSumD:0.3125,},
{ level:null,code:'spsc01',name:'Управление 1',actualStart:'',actualFinish:'',asapStart:'22 02 2007  08 19',asapFinish:'22 02 2007  08 19',compareStart:'',compareFinish:'', critical:null, costTotal:2429.76, volSum:100, durSumD:null,},
{ level:null,code:'sds',name:'ssssssssssssssssss',actualStart:'09 01 2007  08 13',actualFinish:'',asapStart:'17 01 2007  08 00',asapFinish:'02 02 2007  12 00',compareStart:'',compareFinish:'', critical:null, costTotal:98.6, volSum:100, durSumD:18.5,},
{ level:null,code:'4',name:'Длительность',actualStart:'',actualFinish:'',asapStart:'23 01 2007  16 00',asapFinish:'15 02 2007  08 19',compareStart:'',compareFinish:'', critical:null, costTotal:null, volSum:null, durSumD:5,},
{ level:null,code:'5',name:'Длительность',actualStart:'',actualFinish:'',asapStart:'23 01 2007  16 00',asapFinish:'02 02 2007  08 19',compareStart:'',compareFinish:'', critical:null, costTotal:null, volSum:null, durSumD:5,},
{ level:null,code:'6',name:'Длительность',actualStart:'',actualFinish:'',asapStart:'05 02 2007  13 12',asapFinish:'15 02 2007  08 19',compareStart:'',compareFinish:'', critical:null, costTotal:null, volSum:null, durSumD:6,},
],
opLinks: [
{predCode:'spamrd01',succCode:'spamrd04',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spamrd02',succCode:'spamrd04',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spamrd04',succCode:'spammr03',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spscsa03',succCode:'spscsa04',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spscsa04',succCode:'spscic01',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spscsa04',succCode:'spscic02',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spscnc01',succCode:'spscnc02',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'ГЋГЎГєВёГ¬',lagUnit:'% Г®ГЎГєВёГ¬Г ', lag:4,},
{predCode:'spscnc02',succCode:'spscnc03',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spammr03',succCode:'spscsa01',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г„ГҐГ­Гј', lag:5,},
{predCode:'spscsa01',succCode:'spscsa02',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spscsa01',succCode:'spscsa03',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spscic02',succCode:'spscnc01',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spscic01',succCode:'spscnc01',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spamrd03',succCode:'spamrd04',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spamrd01',succCode:'spamrd03',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spamrd02',succCode:'spamrd03',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spammr01',succCode:'spammr02',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spammr02',succCode:'spammr03',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spscsa02',succCode:'spscsa05',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spscsa05',succCode:'spscsa04',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spscsa01',succCode:'spsc01',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spscnc03',succCode:'spsc01',typeSF:'Г”ГЁГ­ГЁГё-Г”ГЁГ­ГЁГё',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spamrd01',succCode:'spscnc03',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spamrd02',succCode:'spscnc03',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spamrd01',succCode:'spammr01',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spamrd01',succCode:'spammr01',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'ГЋГЎГєВёГ¬',lagUnit:'% Г®ГЎГєВёГ¬Г ', lag:56,},
{predCode:'spamrd01',succCode:'spammr01',typeSF:'Г”ГЁГ­ГЁГё-Г”ГЁГ­ГЁГё',lagType:'ГЋГЎГєВёГ¬',lagUnit:'Г…Г¤ГЁГ­ГЁГ¶Г  Г®ГЎГєВёГ¬Г ', lag:56,},
{predCode:'spamrd01',succCode:'spammr01',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spamrd01',succCode:'03',typeSF:'Г‘ГІГ Г°ГІ-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spammr03',succCode:'03',typeSF:'Г”ГЁГ­ГЁГё-Г”ГЁГ­ГЁГё',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'spamrd02',succCode:'03',typeSF:'Г‘ГІГ Г°ГІ-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'4',succCode:'spscnc03',typeSF:'Г‘ГІГ Г°ГІ-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г—Г Г±', lag:null,},
{predCode:'5',succCode:'6',typeSF:'Г”ГЁГ­ГЁГё-Г‘ГІГ Г°ГІ',lagType:'Г‚Г°ГҐГ¬СЏ',lagUnit:'Г„ГҐГ­Гј', lag:4,},
],
};